language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
services:
    - redis-server
install:
    - "pip install --use-mirrors -r requirements.txt"
    - "pip install --use-mirrors coverage"
script: "nosetests --with-coverage --cover-package osmo"
