language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
install:
    - "pip install -r requirements.txt"
    - "pip install -r tests/requirements.txt"
    - "pip install coveralls"
script:
    - "flake8 --max-complexity 10 osmo"
    - "tests/run --with-coverage --cover-package=osmo"
after_failure:
    - "cat tests/log/api"
    - "cat tests/log/publisher"
    - "cat tests/log/redis"
    - "cat tests/log/monitor"
after_success:
    - coveralls
