language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
services:
    - redis-server
install:
    pip install -r requirements-minimal.txt --use-mirrors
before_script:
    - 'osmo/client.py "$PWD/tests/media/" >/dev/null 2>&1 &'
    - 'while ! curl localhost:8000 >/dev/null 2>&1; do sleep 2; done'
script:
    - nosetests
