language: python
python:
    - "2.7"
    - "3.3"
services:
    - redis-server
before_script:
    - 'gunicorn --worker-class=gevent -w 4 -t 99999 osmo.client:app >/dev/null 2>&1 &'
    - 'while ! curl localhost:8000 >/dev/null 2>&1; do sleep 2; done'
script:
    - nosetests
