language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
matrix:
    allow_failures:
        - python: 3.2
services:
    - redis-server
before_script:
    - 'osmo/client.py "$PWD/tests/media/" --test >/dev/null 2>&1 &'
    - 'osmo/publisher.py --test >/dev/null 2>&1 &'
    - 'while ! curl localhost:8000 >/dev/null 2>&1; do sleep 2; done'
script:
    - nosetests
