#!/bin/bash

service_wait_time=2
redis_port=28692

if [[ $0 == /* ]]; then
    location="${0%/*}/.."
else
    location="$PWD/${0#./}"
    location="${location%/*}/.."
fi

redis-server - >/dev/null << EOF &
daemonize no
port $redis_port
EOF

api_pid="$( "$location"/osmo/client.py "$location/tests/media/" > "$location/tests/api.log" 2>&1 & echo "$!" )"
publisher_pid="$( "$location"/osmo/publisher.py --test --port "$redis_port" > "$location/tests/publisher.log" 2>&1 & echo "$!" )"

trap 'kill "$api_pid" ; kill "$publisher_pid" ; redis-cli -p "$redis_port" shutdown' 0

printf 'Waiting %d seconds for services to finish starting...\n\n' "$service_wait_time"
sleep "$service_wait_time"

nosetests "$@"
